config/routes.rb
Rails.application.routes.draw do
  resources :treatments
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "patients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :treatments
end

app/models/treatment.rb
class Treatment < ApplicationRecord
    belongs_to :patient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :age)
    end
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :set_treatment, only: %i[ show edit update destroy ]
  before_action :consulta_pacientes, only: %i[ new edit create update destroy ]
  # GET /treatments or /treatments.json
  def index
    @treatments = Treatment.all
  end

  # GET /treatments/1 or /treatments/1.json
  def show
  end

  # GET /treatments/new
  def new
    @treatment = Treatment.new
  end

  # GET /treatments/1/edit
  def edit
  end

  # POST /treatments or /treatments.json
  def create
    @treatment = Treatment.new(treatment_params)

    respond_to do |format|
      if @treatment.save
        format.html { redirect_to treatment_url(@treatment), notice: "Treatment was successfully created." }
        format.json { render :show, status: :created, location: @treatment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treatments/1 or /treatments/1.json
  def update
    respond_to do |format|
      if @treatment.update(treatment_params)
        format.html { redirect_to treatment_url(@treatment), notice: "Treatment was successfully updated." }
        format.json { render :show, status: :ok, location: @treatment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1 or /treatments/1.json
  def destroy
    @treatment.destroy

    respond_to do |format|
      format.html { redirect_to treatments_url, notice: "Treatment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treatment
      @treatment = Treatment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def treatment_params
      params.require(:treatment).permit(:name, :description, :date, :patient_id)
    end

    def consulta_pacientes
      @patients = Patient.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MedicalCenter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>">
<tr>
  <th scope="row"><%= patient.id %></th>
  <td><%= patient.name %></td>
  <td><%= patient.age %></td>
  <% if patient.treatments.any? %>
  <td><%= patient.treatments.last.name %></td>
  <% end %>
  <td><%= link_to patient, class: 'btn' do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="icon
    icon-tabler icon-tabler-eye-check" width="20" height="20" viewBox="0 0
    24 24" stroke-width="1.5" stroke="#00abfb" fill="none"
    stroke-linecap="round" stroke-linejoin="round">
    <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
    <circle cx="12" cy="12" r="2" />
    <path d="M12 19c-4 0 -7.333 -2.333 -10 -7c2.667 -4.667 6 -7
    10 -7s7.333 2.333 10 7c-.42 .736 -.858 1.414 -1.311 2.033" />
    <path d="M15 19l2 2l4 -4" />
    </svg>
    <% end %>
  </td>
  <td><%= link_to edit_patient_path(patient), class: 'btn' do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler
    icon-tabler-edit" width="20" height="20" viewBox="0 0 24 24"
    stroke-width="1.5" stroke="#ffec00" fill="none" stroke-linecap="round"
    stroke-linejoin="round">
    <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
    <path d="M9 7h-3a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2
    -2v-3" />
    <path d="M9 15h3l8.5 -8.5a1.5 1.5 0 0 0 -3 -3l-8.5 8.5v3" />
    <line x1="16" y1="5" x2="19" y2="8" />
    </svg>
    <% end %>
  </td>
  <td><%= button_to patient, method: :delete, class: 'btn' do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler
    icon-tabler-eraser" width="20" height="20" viewBox="0 0 24 24"
    stroke-width="1.5" stroke="#ff4500" fill="none" stroke-linecap="round"
    stroke-linejoin="round">
    <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
    <path d="M19 19h-11l-4 -4a1 1 0 0 1 0 -1.41l10 -10a1 1 0 0 1
    1.41 0l5 5a1 1 0 0 1 0 1.41l-9 9" />
    <line x1="18" y1="12.3" x2="11.7" y2="6" />
    </svg>
    <% end %>
  </td>
</tr>
</div>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Show this patient", @patient %> |
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/index.html.erb
<%# app/views/patients/index.html.erb %>
<p style="color: green"><%= notice %></p>
<div class="container">
  <h1>Patients</h1>
  <div id="patients">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">Name</th>
          <th scope="col">Age</th>
          <th scope="col">Treatment</th>
          <th scope="col" colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <% @patients.each do |patient| %>
          <%= render patient %>
        <% end %>
      </tbody>
    </table>
    <%= link_to new_patient_path do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler
      icon-tabler-circle-plus" width="32" height="32" viewBox="0 0 24 24"
      stroke-width="1.5" stroke="#009988" fill="none" stroke-linecap="round"
      stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
      <circle cx="12" cy="12" r="9" />
      <line x1="9" y1="12" x2="15" y2="12" />
      <line x1="12" y1="9" x2="12" y2="15" />
      </svg>
    <% end %>
  </div>
</div>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @patient %>

<div>
  <%= link_to "Edit this patient", edit_patient_path(@patient) %> |
  <%= link_to "Back to patients", patients_path %>

  <%= button_to "Destroy this patient", @patient, method: :delete %>
</div>

app/views/treatments/_form.html.erb
<%= form_with(model: treatment) do |form| %>
  <% if treatment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(treatment.errors.count, "error") %> prohibited this treatment from being saved:</h2>

      <ul>
        <% treatment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :patient_id, style: "display: block" %>
    <%= form.collection_select :patient_id, @patients, :id, :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/treatments/_treatment.html.erb
<div id="<%= dom_id treatment %>">
  <tr>
    <td><%= treatment.id %></td>
    <td><%= treatment.name %></td>
    <td><%= treatment.description %></td>
    <td><%= treatment.date %></td>
    <td><%= treatment.patient.name %></td>
    <td><%= link_to treatment, class: 'btn' do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="icon
      icon-tabler icon-tabler-eye-check" width="20" height="20" viewBox="0 0
      24 24" stroke-width="1.5" stroke="#00abfb" fill="none"
      stroke-linecap="round" stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
      <circle cx="12" cy="12" r="2" />
      <path d="M12 19c-4 0 -7.333 -2.333 -10 -7c2.667 -4.667 6 -7
      10 -7s7.333 2.333 10 7c-.42 .736 -.858 1.414 -1.311 2.033" />
      <path d="M15 19l2 2l4 -4" />
      </svg>
      <% end %>
    </td>
    <td><%= link_to edit_treatment_path(treatment), class: 'btn' do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler
      icon-tabler-edit" width="20" height="20" viewBox="0 0 24 24"
      stroke-width="1.5" stroke="#ffec00" fill="none" stroke-linecap="round"
      stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
      <path d="M9 7h-3a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2
      -2v-3" />
      <path d="M9 15h3l8.5 -8.5a1.5 1.5 0 0 0 -3 -3l-8.5 8.5v3" />
      <line x1="16" y1="5" x2="19" y2="8" />
      </svg>
      <% end %>
    </td>
    <td><%= button_to treatment, method: :delete, class: 'btn' do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler
      icon-tabler-eraser" width="20" height="20" viewBox="0 0 24 24"
      stroke-width="1.5" stroke="#ff4500" fill="none" stroke-linecap="round"
      stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
      <path d="M19 19h-11l-4 -4a1 1 0 0 1 0 -1.41l10 -10a1 1 0 0 1
      1.41 0l5 5a1 1 0 0 1 0 1.41l-9 9" />
      <line x1="18" y1="12.3" x2="11.7" y2="6" />
      </svg>
      <% end %>
    </td>
  </tr>
</div>

app/views/treatments/edit.html.erb
<h1>Editing treatment</h1>

<%= render "form", treatment: @treatment %>

<br>

<div>
  <%= link_to "Show this treatment", @treatment %> |
  <%= link_to "Back to treatments", treatments_path %>
</div>

app/views/treatments/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <h1>Treatments</h1>
  <div id="treatments">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">Date</th>
          <th scope="col">Patient</th>
          <th scope="col" colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <% @treatments.each do |treatment| %>
          <%= render treatment %>
        <% end %>
      </tbody>
    </table>
  </div>
    <%= link_to new_treatment_path do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler
      icon-tabler-circle-plus" width="32" height="32" viewBox="0 0 24 24"
      stroke-width="1.5" stroke="#009988" fill="none" stroke-linecap="round"
      stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
      <circle cx="12" cy="12" r="9" />
      <line x1="9" y1="12" x2="15" y2="12" />
      <line x1="12" y1="9" x2="12" y2="15" />
      </svg>
    <% end %>
</div>

app/views/treatments/new.html.erb
<h1>New treatment</h1>

<%= render "form", treatment: @treatment %>

<br>

<div>
  <%= link_to "Back to treatments", treatments_path %>
</div>

app/views/treatments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @treatment %>

<div>
  <%= link_to "Edit this treatment", edit_treatment_path(@treatment) %> |
  <%= link_to "Back to treatments", treatments_path %>

  <%= button_to "Destroy this treatment", @treatment, method: :delete %>
</div>